kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webDevToWebNamespace
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: web
  name: dc64495d-0bf4-4a79-b0f6-61f25ded8847
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apiDevToAPINamespace
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: api
  name: c7a36773-39c1-45ca-9954-71d000c400d7
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webDevToAPINamespace
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: api
  name: dc64495d-0bf4-4a79-b0f6-61f25ded8847
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apiDevToWEBNamespace
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: web
  name: c7a36773-39c1-45ca-9954-71d000c400d7
