apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  selector:
    matchLabels:
      run: user-java
  replicas: 1
  template:
    metadata:
      labels:
        run: user-java
    spec:
      containers:
      - name: user-java
        image: registryqrc0144.azurecr.io/user-java:1.0
        env:
        - name: SQL_USER
          value: "sqladminqRc0144"
        - name: SQL_PASSWORD
          value: "cJ7lt1Za0"
        - name: SQL_SERVER
          value: "sqlserverqrc0144.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  labels:
    run: user-java
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: user-java